version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.ssl.conf:/etc/nginx/conf.d/default.conf
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot -w /var/www/certbot -d yourdomain.com -d www.youurdomain.com --email example@example.com --agree-tos --non-interactive --dry-run
    depends_on:
      - nginx
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
