version: '3'

services:
  backend:
    env_file:
      - .env.dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
      - memcached
    volumes:
      - uploads-volume:/app/uploads

  db:
    env_file:
      - .env.dev
    image: postgres:13
    environment:
      POSTGRES_DB: critboard_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - app-dist:/usr/share/nginx/html
      - uploads-volume:/usr/share/nginx/html/uploads
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./etc/letsencrypt:/etc/letsencrypt


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - app-dist:/app/dist

volumes:
  pgdata:
  uploads-volume:
  app-dist:
