version: '3'

services:
  backend:
    env_file:
      - .env.dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - uploads-volume:/app/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - uploads-volume:/usr/share/nginx/html/uploads

  db:
    env_file:
      - .env.dev
    image: postgres:13
    environment:
      POSTGRES_DB: critboard_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
  uploads-volume:
