version: '3'

services:
  backend:
    env_file:
      - .env.dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
      - memcached
    volumes:
      - uploads-volume:/app/uploads

  db:
    env_file:
      - .env.dev
    image: postgres:13
    environment:
      POSTGRES_DB: critboard_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend  # Added frontend dependency here
    volumes:
      - app-dist:/usr/share/nginx/html
      - uploads-volume:/usr/share/nginx/html/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app-dist:/app/dist
    # Removed the ports directive as Nginx will handle requests to frontend

volumes:
  pgdata:
  uploads-volume:
  app-dist:
